In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch import nn

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
data.shape

(569, 33)

In [6]:
data= data.drop(['Unnamed: 32','id'], axis =1)

In [7]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [8]:
data.shape

(569, 31)

In [9]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [10]:
X= data.drop(columns=['diagnosis'],axis=1)
y=data['diagnosis']

In [11]:
y= LabelEncoder().fit_transform(y)

In [12]:
X = torch.tensor(X.values).type(torch.float)

In [13]:
y= torch.tensor(y).type(torch.LongTensor)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
X

tensor([[1.7990e+01, 1.0380e+01, 1.2280e+02,  ..., 2.6540e-01, 4.6010e-01,
         1.1890e-01],
        [2.0570e+01, 1.7770e+01, 1.3290e+02,  ..., 1.8600e-01, 2.7500e-01,
         8.9020e-02],
        [1.9690e+01, 2.1250e+01, 1.3000e+02,  ..., 2.4300e-01, 3.6130e-01,
         8.7580e-02],
        ...,
        [1.6600e+01, 2.8080e+01, 1.0830e+02,  ..., 1.4180e-01, 2.2180e-01,
         7.8200e-02],
        [2.0600e+01, 2.9330e+01, 1.4010e+02,  ..., 2.6500e-01, 4.0870e-01,
         1.2400e-01],
        [7.7600e+00, 2.4540e+01, 4.7920e+01,  ..., 0.0000e+00, 2.8710e-01,
         7.0390e-02]])

In [16]:
model = nn.Sequential(
    nn.Linear(in_features=30,out_features=30),
    nn.ReLU(),
    nn.Linear(in_features=30,out_features=30),
    nn.ReLU(),
    nn.Linear(in_features=30,out_features=2),
    nn.Sigmoid()
)

In [17]:
model

Sequential(
  (0): Linear(in_features=30, out_features=30, bias=True)
  (1): ReLU()
  (2): Linear(in_features=30, out_features=30, bias=True)
  (3): ReLU()
  (4): Linear(in_features=30, out_features=2, bias=True)
  (5): Sigmoid()
)

In [18]:
list(model.parameters())

[Parameter containing:
 tensor([[-7.8521e-02,  7.9846e-02,  1.8085e-01, -1.8006e-01,  2.3490e-03,
           1.1999e-01, -7.3568e-02,  1.8184e-01, -1.6703e-01,  6.6563e-02,
          -7.4143e-03,  7.5122e-02,  8.7839e-02, -2.9029e-02,  1.2605e-01,
          -3.0831e-03, -1.6473e-01, -8.6529e-03, -8.6666e-03, -2.2221e-02,
          -7.4573e-02, -1.6139e-01, -1.2540e-01,  1.6817e-01,  4.5401e-03,
           1.5597e-01, -1.1480e-01,  8.7036e-02,  1.2562e-01, -6.1065e-02],
         [-1.4935e-02, -9.5299e-02, -4.5363e-02, -7.1741e-02, -1.6639e-01,
          -1.6159e-02, -5.1342e-02, -2.1831e-02,  1.1642e-01, -2.7597e-02,
          -5.0332e-02, -6.1371e-03, -1.3627e-01, -8.1036e-02,  3.9322e-02,
           5.1386e-02, -3.0866e-02,  7.5208e-03, -1.4087e-01,  7.6169e-02,
          -1.2815e-01,  1.1340e-01,  1.2531e-01,  1.5934e-01, -1.2690e-01,
           1.0272e-01,  4.3804e-02, -1.2722e-01, -1.6236e-01,  5.6884e-02],
         [-8.5788e-02, -1.1618e-01,  4.2572e-02, -9.1735e-02,  5.2643e-02,


In [19]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-7.8521e-02,  7.9846e-02,  1.8085e-01, -1.8006e-01,  2.3490e-03,
                        1.1999e-01, -7.3568e-02,  1.8184e-01, -1.6703e-01,  6.6563e-02,
                       -7.4143e-03,  7.5122e-02,  8.7839e-02, -2.9029e-02,  1.2605e-01,
                       -3.0831e-03, -1.6473e-01, -8.6529e-03, -8.6666e-03, -2.2221e-02,
                       -7.4573e-02, -1.6139e-01, -1.2540e-01,  1.6817e-01,  4.5401e-03,
                        1.5597e-01, -1.1480e-01,  8.7036e-02,  1.2562e-01, -6.1065e-02],
                      [-1.4935e-02, -9.5299e-02, -4.5363e-02, -7.1741e-02, -1.6639e-01,
                       -1.6159e-02, -5.1342e-02, -2.1831e-02,  1.1642e-01, -2.7597e-02,
                       -5.0332e-02, -6.1371e-03, -1.3627e-01, -8.1036e-02,  3.9322e-02,
                        5.1386e-02, -3.0866e-02,  7.5208e-03, -1.4087e-01,  7.6169e-02,
                       -1.2815e-01,  1.1340e-01,  1.2531e-01,  1.5934e-01, -1.2690e-01,
     

In [20]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [21]:
from tqdm.auto import tqdm

torch.manual_seed(42)

epochs =100

for epoch in tqdm(range(epochs)):
    y_pred = model(X_train)
    loss = (loss_fn(y_pred,y_train))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    model.eval()
    with torch.inference_mode():
        # 1. Forward pass
        test_logits = model(X_test).squeeze()
        test_pred = torch.round(torch.sigmoid(test_logits))
        # 2. Caculate loss/accuracy
        test_loss = loss_fn(test_logits,
                            y_test)

    # Print out what's happening every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f} | Test loss: {test_loss:.5f}")

  0%|          | 0/100 [00:00<?, ?it/s]

Epoch: 0 | Loss: 0.93966 | Test loss: 0.69346
Epoch: 10 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 20 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 30 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 40 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 50 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 60 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 70 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 80 | Loss: 0.68469 | Test loss: 0.69045
Epoch: 90 | Loss: 0.68469 | Test loss: 0.69045
